In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [44]:
# read the data
data = pd.read_csv('data/train.csv')
data_test = pd.read_csv('data/test.csv')

# look at what is there
display(data.head(10))
display(data_test.head(10))

,Id,Subject Focus,Eyes,Face,Near,Action,Accessory,Group,Collage,Human,Occlusion,Info,Blur,Pawpularity
0,0007de18844b0dbbb5e1f607da0606e0,0,1,1,1,0,0,1,0,0,0,0,0,63
1,0009c66b9439883ba2750fb825e1d7db,0,1,1,0,0,0,0,0,0,0,0,0,42
2,0013fd999caf9a3efe1352ca1b0d937e,0,1,1,1,0,0,0,0,1,1,0,0,28
3,0018df346ac9c1d8413cfcc888ca8246,0,1,1,1,0,0,0,0,0,0,0,0,15
4,001dc955e10590d3ca4673f034feeef2,0,0,0,1,0,0,1,0,0,0,0,0,72
5,001dd4f6fafb890610b1635f967ea081,0,0,1,0,0,0,0,0,0,0,0,1,74
6,0023b8a3abc93c712edd6120867deb53,0,1,1,1,0,0,0,0,1,1,0,0,22
7,0031d6a9ef7340f898c3e05f92c7bb04,0,1,1,0,0,0,1,1,0,0,1,0,35
8,0042bc5bada6d1cf8951f8f9f0d399fa,0,1,1,1,0,0,0,0,0,0,0,0,53
9,0049cb81313c94fa007286e9039af910,0,1,1,1,0,0,0,0,0,0,0,0,21

,Id,Subject Focus,Eyes,Face,Near,Action,Accessory,Group,Collage,Human,Occlusion,Info,Blur
0,4128bae22183829d2b5fea10effdb0c3,1,0,1,0,0,1,1,0,0,1,0,1
1,43a2262d7738e3d420d453815151079e,0,1,0,0,0,0,1,1,0,0,0,0
2,4e429cead1848a298432a0acad014c9d,0,0,0,1,0,1,1,1,0,1,1,1
3,80bc3ccafcc51b66303c2c263aa38486,1,0,1,0,0,0,0,0,0,0,1,0
4,8f49844c382931444e68dffbe20228f4,1,1,1,0,1,1,0,1,0,1,1,0
5,b03f7041962238a7c9d6537e22f9b017,0,0,1,1,1,1,1,1,1,0,1,0
6,c978013571258ed6d4637f6e8cc9d6a3,1,0,0,0,1,1,0,1,0,1,1,1
7,e0de453c1bffc20c22b072b34b54e50f,1,0,1,0,0,0,0,0,1,0,0,1

In [45]:
# get the y and x values
y = data['Pawpularity']
X = data.drop(['Id', 'Pawpularity'], axis=1)
X_test = data_test.drop(['Id'], axis=1)


def addones(X):
    """Add a row of ones to the X matrix"""
    iota = np.ones((len(X), 1))
    X = np.hstack((iota, X))
    return X

X = addones(X)
X_test = addones(X_test)

In [46]:
def norm(X,y):
    """calculate the linear coefficients with X an y"""
    b = np.linalg.inv(X.T @ X) @ X.T @ y
    return b

b = norm(X,y)
print(b)

[37.37044198 -1.12584593 -2.48009618  2.45013923  0.46844535 -0.3088989
  1.21101048  1.21999797  0.39700325  0.36362689 -0.06627373 -0.71553513
 -3.75364608]

In [47]:
def costs(X, y, b):
    """Get the costs"""
    e = y - X @ b
    cost = 1 / len(y) * e.T @ e
    return cost

In [48]:
cost = costs(X,y,b) 
print(cost)

422.9657919854776

In [49]:
# Get the y_test values
y_test = X_test @ b
print(y_test)

[37.30582393 36.50734701 36.13144409 37.97920015 36.73194507 42.45623111
 33.00825594 35.30471609]